"""add likeg models

Revision ID: 585d5c4ee77d
Revises: 4dca3d1814dd
Create Date: 2019-05-26 00:30:39.835644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585d5c4ee77d'
down_revision = '4dca3d1814dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
